<link rel="stylesheet" href="{{asset('/front-end')}}/css/bootstrap.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/linericon/style.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/css/font-awesome.min.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/css/themify-icons.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/css/flaticon.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/owl-carousel/owl.carousel.min.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/lightbox/simpleLightbox.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/nice-select/css/nice-select.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/animate-css/animate.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/vendors/jquery-ui/jquery-ui.css" />
<!-- main css -->
<link rel="stylesheet" href="{{asset('/front-end')}}/css/style.css" />
<link rel="stylesheet" href="{{asset('/front-end')}}/css/responsive.css" />
